// <auto-generated />
using GestorCursosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSW1_T1_PianaVeraGrace.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestorCursosApi.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<int>("NivelAcademicoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CursoId");

                    b.HasIndex("NivelAcademicoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("GestorNivelAcademicoApi.Models.NivelAcademico", b =>
                {
                    b.Property<int>("NivelAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NivelAcademicoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("NivelAcademicoId");

                    b.ToTable("NivelesAcademicos");
                });

            modelBuilder.Entity("GestorCursosApi.Models.Curso", b =>
                {
                    b.HasOne("GestorNivelAcademicoApi.Models.NivelAcademico", "NivelAcademico")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelAcademico");
                });

            modelBuilder.Entity("GestorNivelAcademicoApi.Models.NivelAcademico", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
